machinery:
    image: kerberos/machinery
    ports:
    - "8889"

web:
    image: kerberos/web
    environment:
    - KERBEROSIO_SECURE_SSL=false
    ports:
    - "80"
    volumes_from:
    - machinery
    links:
    - machinery
